[env]
CARGO_WORKSPACE_DIR = { value = "", relative = true }

[alias]
xtask = "run --package xtask --"
clippy-wrapper = "run --package clippy-wrapper --"

lint = "clippy-wrapper lint"
fixit = "clippy-wrapper fixit"
